# Generated by Django 4.1.5 on 2023-01-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Parent",
            new_name="Guardian",
        ),
    ]
