# Generated by Django 4.1.5 on 2023-01-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_guardian_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
