# Generated by Django 4.1.5 on 2023-01-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
        ("students", "0004_guardian_is_deleted_student_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="active_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.class",
            ),
        ),
    ]
