# Generated by Django 4.1.5 on 2023-01-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("grade", "section")},
        ),
    ]
