# Generated by Django 4.1.5 on 2023-01-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_alter_class_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="name",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                ],
                max_length=2,
            ),
        ),
    ]
