# Generated by Django 4.1.5 on 2023-01-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0004_class_teachers_alter_grade_name_alter_section_name"),
        ("teachers", "0002_remove_teacher_classes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=200)),
                ("sub", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=200)),
                ("classes", models.ManyToManyField(to="classes.class")),
                ("teachers", models.ManyToManyField(to="teachers.teacher")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
